blank_issues_enabled: true

contact_links:
  - name: Minecraft Java Edition Related Bug 🔐
    url: https://bugs.mojang.com/projects/MC/issues/
    about: We love Minecraft and would love to help, but this probably isn't quite the right place :-). Please submit Minecraft related issues to the Mojang folks will take the first pass at triaging the issue. If it is a genuine Microsoft Build of OpenJDK (Java/JVM) issue, then they'll open an issue with us and we'll work together to reolve it. For context, most Java crash reports with Minecraft are the result of Java calling a buggy native library, O/S driver or similar. So although you'll see a _Java_ crash report, the root cause is typically inside the other library.
