name: Check Minecraft crash
on:
  issues:
    types: [opened]

jobs:
  check-minecraft-crash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install axios
      - name: Check Minecraft crash
        uses: actions/github-script@v5
        with:
          script: |
            // Strings which indicate that Minecraft is modded
            const moddedStrings = [
              'net.fabricmc.loader.launch.knot.KnotClient',
              'net.fabricmc.loader.impl.launch.knot.KnotClient', // new class name
              '--version fabric-loader-',
              '--tweakClass optifine.OptiFineTweaker',
            ]

            const axios = require('axios')

            async function httpGet(url) {
              const result = await axios.get(url, {
                responseType: 'text'
              })
              const status = result.status
              const data = result.data
              if (status < 200 || status >= 300) {
                throw new Error(`GET request to ${url} failed with ${status} '${result.statusText}': ${data}`)
              }
              return data
            }

            const issueNumber = context.issue.number
            const owner = context.repo.owner
            const repo = context.repo.repo
            const issueData = (await github.rest.issues.get({
              owner: owner,
              repo: repo,
              issue_number: issueNumber,
            })).data
            const issueTitle = issueData.title
            const issueBody = issueData.body

            const foundModdedStrings = moddedStrings.filter(s => issueBody.includes(s))
            if (foundModdedStrings.length === 0) {
              console.log('Did not find modded string in issue body, searching attachments')
              // Try searching in attachments
              // There is currently no API so try to find URL then get attachment content, see https://github.community/t/get-files-attached-in-issue/117443
              const attachmentPattern = new RegExp(`https://github\\.com/${owner}/${repo}/files/\\d+/[a-zA-Z0-9_\\-.]+`, 'g')
              const attachmentUrls = Array.from(issueBody.matchAll(attachmentPattern), m => m[0])
              console.log('Found attachment URLs', attachmentUrls)
              for (const url of attachmentUrls) {
                let attachment = undefined
                try {
                  attachment = await httpGet(url)
                } catch (e) {
                  // Only log message because complete error is rather verbose
                  console.log('Failed getting attachment for ' + url, e.message)
                  continue
                }
                moddedStrings.forEach(s => {
                  if (attachment.includes(s)) {
                    foundModdedStrings.push(s)
                  }
                })
              }
            }

            // Uses lookbehind and lookahead instead of \W to match start and end of string as well
            const minecraftRegex = /(?<!\w)Minecraft(?!\w)/i
            const isMinecraftIssue = minecraftRegex.test(issueTitle) || minecraftRegex.test(issueBody)
            console.log('Is Minecraft issue: ' + isMinecraftIssue)

            let addReportToMojangComment = true

            if (foundModdedStrings.length === 0) {
              console.log('Did not find modded strings')
            } else {
              console.log('Found modded strings', foundModdedStrings)

              // Don't tell user to report modded crashes on Mojira; they will be considered Invalid
              addReportToMojangComment = false

              // Only comment, and close issue. If user believes this was a false positive, ask them to reopen.
              github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: issueNumber,
                body: (
                  'It looks like you are using a modified version of Minecraft. The following was detected in your crash report:\n```\n'
                  + foundModdedStrings.join('\n')
                  + '\n```\nPlease report this crash to the mod creator. If you can also reproduce this crash without having any mods installed, please attach that crash report here as well.'
                  + '\nIf you are not using a mod and believe this is an OpenJDK bug, please reopen the issue.'
                )
              })
            }

            if (isMinecraftIssue) {
              if (addReportToMojangComment) {
                github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: issueNumber,
                  body: (
                    'Thank you for the report!\n'
                    + 'Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). '
                    + 'Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). '
                    + 'The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.'
                  )
                })
              }

              // add Minecraft label
              github.rest.issues.addLabels({
                owner: owner,
                repo: repo,
                issue_number: issueNumber,
                labels: ['Minecraft']
              })

              // We will close any Minecraft-related issue automatically.
              github.rest.issues.update({
                owner: owner,
                repo: repo,
                issue_number: issueNumber,
                state: 'closed'
              })
            }
